In [45]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, BatchNormalization, Flatten, Dense, Dropout
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

In [46]:
# Load MNIST dataset.
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [47]:
# Normalize pixel values to 0-1
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

In [48]:
# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [49]:
# Reshape input to 4D tensor
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [50]:
# Define AlexNet model
model = tf.keras.models.Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 1), padding='same'),
    MaxPooling2D(pool_size=(2, 2), strides=(2,2)),
    BatchNormalization(),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2, 2), strides=(2,2)),
    BatchNormalization(),
    Conv2D(128, (3,3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2, 2), strides=(2,2)),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

In [51]:
#Summary of the architectural model
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_22 (Conv2D)          (None, 28, 28, 32)        320       
                                                                 
 max_pooling2d_16 (MaxPoolin  (None, 14, 14, 32)       0         
 g2D)                                                            
                                                                 
 batch_normalization_4 (Batc  (None, 14, 14, 32)       128       
 hNormalization)                                                 
                                                                 
 conv2d_23 (Conv2D)          (None, 14, 14, 64)        18496     
                                                                 
 max_pooling2d_17 (MaxPoolin  (None, 7, 7, 64)         0         
 g2D)                                                            
                                                      

In [52]:
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
# Train the model
model.fit(X_train, y_train, batch_size=32, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
1875/1875 [==============================] - 73s 38ms/step - loss: 0.3137 - accuracy: 0.9040 - val_loss: 0.0813 - val_accuracy: 0.9755
Epoch 2/5
1875/1875 [==============================] - 72s 38ms/step - loss: 0.1106 - accuracy: 0.9714 - val_loss: 0.0347 - val_accuracy: 0.9890
Epoch 3/5
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0796 - accuracy: 0.9800 - val_loss: 0.0440 - val_accuracy: 0.9883
Epoch 4/5
1875/1875 [==============================] - 83s 44ms/step - loss: 0.0629 - accuracy: 0.9837 - val_loss: 0.0272 - val_accuracy: 0.9924
Epoch 5/5
1875/1875 [==============================] - 78s 42ms/step - loss: 0.0553 - accuracy: 0.9862 - val_loss: 0.0413 - val_accuracy: 0.9895


In [54]:
# Evaluate the model
import numpy as np
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

313/313 [==============================] - 3s 10ms/step - loss: 0.0413 - accuracy: 0.9895
Test accuracy: 0.9894999861717224


In [55]:
# Make predictions
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

313/313 [==============================] - 3s 9ms/step


In [56]:
# Print classification report and confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print('\nClassification Report:\n', classification_report(np.argmax(y_test, axis=1), y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(np.argmax(y_test, axis=1), y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       1.00      0.99      0.99      1135
           2       0.99      0.98      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.98      0.99      0.99      1028
           8       0.97      1.00      0.98       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000


Confusion Matrix:
 [[ 977    0    0    0    0    0    0    1    2    0]
 [   0 1125    1    3    0    1    1    1    3    0]
 [   1    0 1016    0    0    0    1    6    8    0]
 [   0    0    0 1002    0    2    0 